### ISSUE TITLE
PSA: 3DiScord is dead and can get you banned!

### ISSUE THREAD

**Issue by sks316** [cheuble/3DiScord#22] opened 2018-01-01 23:59 UTC
Basically, the application doesn't use websockets and spams the API instead. If you want to know more, click the link below.
http://gbatemp.net/entry/about-3discord.13037/

**Comment by cheuble** [comment] 2018-01-02 00:04
This shouldn't be a real issue...
Besides, it's a duplicate of #9

**Closed as completed by cheuble** 2018-01-02 00:04 UTC
Labels: duplicate

**Comment by sks316** [comment] 2018-01-02 00:08
I just thought people should know it's dead and can get you banned since that isn't explicitly stated in #9, so...
